package com.ajoshow.exam1z0813;

import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

public class NumberFormatMain {

    public static void main(String[] args) throws ParseException {

        //  if you rectify the exception problem, the output will depend
        // on which location in which you run this program. For example,
        // if you run it on a machine with US as the Locale, it will print
        // two unequal numbers because the string generated by the formatter
        // created using French locale will be 123 456,789.
        // This will not be parsed correctly by the second formatter,
        // which is created using the default locale (which is US).
        // In fact, it will parse it as 123.
        double amount = 123456.789;
        Locale fr = new Locale("fr", "FR");
        NumberFormat formatter = NumberFormat.getInstance(fr);
        String s = formatter.format(amount) ;
        formatter = NumberFormat.getInstance();
        Number amount2 = formatter.parse(s);
        System.out.println( amount + " " + amount2 );

    }
}
